import os, re, sys
sys.dont_write_bytecode = 1

import gen_mul4 as P

g_n = int(sys.argv[1])
g_tgt = sys.argv[2]

g_code = '''
mp_limb_t
subtract_lesser_from_bigger_@(mp_ptr tgt, mp_srcptr up, mp_srcptr vp) {
    mp_limb_t less;
    mpn_le_@(less, up, vp);
    if(less) {
        mpn_sub@(tgt, vp, up);
    } else {
        mpn_sub@(tgt, up, vp);
    }
    return less;
}
'''.replace('@', '%s' % g_n)

def do_it(tgt):
    tgt.write(P.g_autogenerated_patt % os.path.basename(sys.argv[0]))
    tgt.write(g_code.strip() + '\n')

try:
    os.makedirs(os.path.dirname(g_tgt))
except:
    pass

with open(g_tgt, 'wb') as g_o:
    do_it(g_o)
